# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-19 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20181019_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='users',
        ),
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='first_app.User'),
            preserve_default=False,
        ),
    ]
